echo 'pub fn part_1(lines:&Vec<String>) -> i32{0}pub fn part_2(lines:&Vec<String>) -> i32{0}' >day01.rs
echo 'pub fn part_1(lines:&Vec<String>) -> i32{0}pub fn part_2(lines:&Vec<String>) -> i32{0}' >day02.rs
echo 'pub fn part_1(lines:&Vec<String>) -> i32{0}pub fn part_2(lines:&Vec<String>) -> i32{0}' >day03.rs
echo 'pub fn part_1(lines:&Vec<String>) -> i32{0}pub fn part_2(lines:&Vec<String>) -> i32{0}' >day04.rs
echo 'pub fn part_1(lines:&Vec<String>) -> i32{0}pub fn part_2(lines:&Vec<String>) -> i32{0}' >day05.rs
echo 'pub fn part_1(lines:&Vec<String>) -> i32{0}pub fn part_2(lines:&Vec<String>) -> i32{0}' >day06.rs
echo 'pub fn part_1(lines:&Vec<String>) -> i32{0}pub fn part_2(lines:&Vec<String>) -> i32{0}' >day07.rs
echo 'pub fn part_1(lines:&Vec<String>) -> i32{0}pub fn part_2(lines:&Vec<String>) -> i32{0}' >day08.rs
echo 'pub fn part_1(lines:&Vec<String>) -> i32{0}pub fn part_2(lines:&Vec<String>) -> i32{0}' >day09.rs
echo 'pub fn part_1(lines:&Vec<String>) -> i32{0}pub fn part_2(lines:&Vec<String>) -> i32{0}' >day10.rs
echo 'pub fn part_1(lines:&Vec<String>) -> i32{0}pub fn part_2(lines:&Vec<String>) -> i32{0}' >day11.rs
echo 'pub fn part_1(lines:&Vec<String>) -> i32{0}pub fn part_2(lines:&Vec<String>) -> i32{0}' >day12.rs
echo 'pub fn part_1(lines:&Vec<String>) -> i32{0}pub fn part_2(lines:&Vec<String>) -> i32{0}' >day13.rs
echo 'pub fn part_1(lines:&Vec<String>) -> i32{0}pub fn part_2(lines:&Vec<String>) -> i32{0}' >day14.rs
echo 'pub fn part_1(lines:&Vec<String>) -> i32{0}pub fn part_2(lines:&Vec<String>) -> i32{0}' >day15.rs
echo 'pub fn part_1(lines:&Vec<String>) -> i32{0}pub fn part_2(lines:&Vec<String>) -> i32{0}' >day16.rs
echo 'pub fn part_1(lines:&Vec<String>) -> i32{0}pub fn part_2(lines:&Vec<String>) -> i32{0}' >day17.rs
echo 'pub fn part_1(lines:&Vec<String>) -> i32{0}pub fn part_2(lines:&Vec<String>) -> i32{0}' >day18.rs
echo 'pub fn part_1(lines:&Vec<String>) -> i32{0}pub fn part_2(lines:&Vec<String>) -> i32{0}' >day19.rs
echo 'pub fn part_1(lines:&Vec<String>) -> i32{0}pub fn part_2(lines:&Vec<String>) -> i32{0}' >day20.rs
echo 'pub fn part_1(lines:&Vec<String>) -> i32{0}pub fn part_2(lines:&Vec<String>) -> i32{0}' >day21.rs
echo 'pub fn part_1(lines:&Vec<String>) -> i32{0}pub fn part_2(lines:&Vec<String>) -> i32{0}' >day22.rs
echo 'pub fn part_1(lines:&Vec<String>) -> i32{0}pub fn part_2(lines:&Vec<String>) -> i32{0}' >day23.rs
echo 'pub fn part_1(lines:&Vec<String>) -> i32{0}pub fn part_2(lines:&Vec<String>) -> i32{0}' >day24.rs
echo 'pub fn part_1(lines:&Vec<String>) -> i32{0}pub fn part_2(lines:&Vec<String>) -> i32{0}' >day25.rs
